[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

# Chain ID 31 = Rootstock Testnet
# Chain ID 30 = Rootstock Mainnet
[rpc_endpoints]
rootstock_testnet = "${ROOTSTOCK_TESTNET_RPC}"
rootstock_mainnet = "${ROOTSTOCK_MAINNET_RPC}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
